Illegal C++11 narrowing (#3369)
With clang-cl, the current code on Windows:
```
  struct timeval tv = { (time_t)timeout /* sec */, 0 };
```
gives this error:
```
NetworkDiscovery.cpp(686,25): error: non-constant-expression cannot be narrowed from type 'time_t' (aka 'long long') to 'long' in
      initializer list [-Wc++11-narrowing]
  struct timeval tv = { (time_t)timeout /* sec */, 0 };
                        ^~~~~~~~~~~~~~~
```

Since Winsock (for historic reasons) declares a `tv_sec` as a `long`) and a `time_t` as a 64-bit `__int64`.
To avoid this issue I was forced use build with `-D_USE_32BIT_TIME_T_`, but that seemed completely wrong.
Hence this patch.

Besides the `timeout` should be at least 1 sec.